services:
  web:
    image: caddy:alpine
    restart: unless-stopped
    stop_grace_period: 1s
    volumes:
      - ../dist:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  backend:
    image: node:alpine
    restart: unless-stopped
    stop_grace_period: 1s
    working_dir: /app
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env
    volumes:
      - ../package.json:/app/package.json:ro
      - ../package-lock.json:/app/package-lock.json:ro
      - ../dist/backend:/app/dist/backend:ro
      - backend_node_modules:/app/node_modules
    command: sh -c "npm ci --omit=dev --ignore-scripts && node dist/backend/server.js"

volumes:
  backend_node_modules: