# Production overrides
services:
  web:
    labels:
      caddy: test.mariozechner.at
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - default
      - caddy-network

  backend:
    networks:
      - default

networks:
  caddy-network:
    external: true