# Production overrides
services:
  web:
    labels:
      caddy: static files only by the 2. test.mariozechner.at
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true